keyworddocument = {
	'Add Time To Date' : ["Adds time to date and returns the resulting date.", " ", "Arguments:", "date: Date to add time to in one of the supported date formats.","time: Time that is added in one of the supported time formats.","result_format: Format of the returned date.", "exclude_millis: When set to any true value, rounds and drops milliseconds as explained in millisecond handling.","date_format: Possible custom timestamp format of date."],
	
	'Add Time To Time' : ["Adds time to another time and returns the resulting time.","Arguments:","time1: First time in one of the supported time formats.","time2: Second time in one of the supported time formats.","result_format: Format of the returned time.","exclude_millis: When set to any true value, rounds and drops milliseconds as explained in millisecond handling."],
	
	'Convert Date' : ["Converts between supported date formats.","Arguments:","date: Date in one of the supported date formats.","result_format: Format of the returned date.","exclude_millis: When set to any true value, rounds and drops milliseconds as explained in millisecond handling.","date_format: Specifies possible custom timestamp format."],
	
	'Get Current Date' : ["Returns current local or UTC time with an optional increment.","Arguments:","time_zone: Get the current time on this time zone. Currently only local (default) and UTC are supported.","increment: Optional time increment to add to the returned date in one of the supported time formats. Can be negative.","result_format: Format of the returned date (see date formats).","exclude_millis: When set to any true value, rounds and drops milliseconds as explained in millisecond handling."],
	
	'Subtract Date From Date' : ["Subtracts date from another date and returns time between.","Arguments:","date1: Date to subtract another date from in one of the supported date formats.","date2: Date that is subtracted in one of the supported date formats.","result_format: Format of the returned time (see time formats).","exclude_millis: When set to any true value, rounds and drops milliseconds as explained in millisecond handling.","date1_format: Possible custom timestamp format of date1.","date2_format: Possible custom timestamp format of date2."],
	
	'Subtract Time From Date' : ["Subtracts time from date and returns the resulting date.","Arguments:","date: Date to subtract time from in one of the supported date formats.","time: Time that is subtracted in one of the supported time formats.","result_format: Format of the returned date.","exclude_millis: When set to any true value, rounds and drops milliseconds as explained in millisecond handling.","date_format: Possible custom timestamp format of date."],
	
	'Subtract Time From Time' : ["Subtracts time from another time and returns the resulting time.","Arguments:","time1: Time to subtract another time from in one of the supported time formats.","time2: Time to subtract in one of the supported time formats.","result_format: Format of the returned time.","exclude_millis: When set to any true value, rounds and drops milliseconds as explained in millisecond handling."],
	
	'Click Element' : ["Click the element identified by locator.","See the Locating elements section for details about the locator syntax.","The modifier argument can be used to pass Selenium Keys when clicking the element. The + can be used as a separator for different Selenium Keys. The CTRL is internally translated to the CONTROL key. The modifier is space and case insensitive, example 'alt' and ' aLt ' are supported formats to ALT key . If modifier does not match to Selenium Keys, keyword fails.","If action_chain argument is true, see Boolean arguments for more details on how to set boolean argument, then keyword uses ActionChain based click instead of the <web_element>.click() function. If both action_chain and modifier are defined, the click will be performed using modifier and action_chain will be ignored."],

	'Wait Until Page Contains element' : ["Waits until the element locator appears on the current page.","Fails if timeout expires before the element appears. See the Timeouts section for more information about using timeouts and their default value and the Locating elements section for details about the locator syntax.","error can be used to override the default error message","The limit argument can used to define how many elements the page should contain. When limit is None (default) page can contain one or more elements. When limit is a number, page must contain same number of elements.","limit is new in SeleniumLibrary 4.4"]

	

}